# Generated by Django 4.0.4 on 2022-06-17 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                blank=True, help_text="Corps de la critique.", max_length=8192
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(help_text="Titre de la critique.", max_length=128),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Note de la critique allant de 1 à 5.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description relative à la demande.",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                help_text="Titre du livre ou de l'article de la demande.",
                max_length=128,
            ),
        ),
    ]
